# Generated by Django 4.2.4 on 2023-09-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortifoliosSite', '0002_user_github_user_linkedin_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='resumo',
            field=models.TextField(max_length=499),
        ),
    ]
